networks:
  net:

volumes:
  postgres-test-data:
  redis-test-data:

services:
  backend:
    container_name: backend
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres-test
      - redis-test
    networks:
      - net
    ports:
      - "8000:8000"


  postgres-test:
    container_name: postgres-test
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
    - net

  redis-test:
    container_name: redis-test
    image: redis:latest
    env_file: .env
    volumes:
      - redis-test-data:/data
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - net