networks:
  net:

volumes:
  postgres-test-data:
  redis-test-data:

services:

  postgres-test:
    container_name: postgres-test
    image: postgres:latest
    env_file: .env.local
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
    - net

  redis-test:
    container_name: redis-test
    image: redis:latest
    env_file: .env.local
    volumes:
      - redis-test-data:/data
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - net