"""init_database

Revision ID: 54f7fdc909ae
Revises:
Create Date: 2025-05-11 17:46:30.372690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54f7fdc909ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Название предмета"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="feature",
    )
    op.create_table(
        "image",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image", sa.String(), nullable=False, comment="Ссылка на картинку"),
        sa.Column(
            "active", sa.Boolean(), nullable=False, comment="Флаг доступности картинки"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="image",
    )
    op.create_table(
        "worker",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Название обработчика"),
        sa.Column(
            "capacity",
            sa.Integer(),
            nullable=False,
            comment="Максимальное число картинок для одновременной обработки",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="worker",
    )
    op.create_index(
        op.f("ix_worker_worker_name"), "worker", ["name"], unique=True, schema="worker"
    )
    op.create_table(
        "image_x_feature",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["feature.feature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image.image.id"],
        ),
        sa.PrimaryKeyConstraint("image_id", "feature_id"),
        schema="feature",
    )
    op.create_index(
        op.f("ix_feature_image_x_feature_feature_id"),
        "image_x_feature",
        ["feature_id"],
        unique=False,
        schema="feature",
    )
    op.create_index(
        op.f("ix_feature_image_x_feature_image_id"),
        "image_x_feature",
        ["image_id"],
        unique=False,
        schema="feature",
    )
    op.create_table(
        "worker_x_feature",
        sa.Column("worker_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_id"],
            ["feature.feature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.worker.id"],
        ),
        sa.PrimaryKeyConstraint("worker_id", "feature_id"),
        schema="feature",
    )
    op.create_index(
        op.f("ix_feature_worker_x_feature_worker_id"),
        "worker_x_feature",
        ["worker_id"],
        unique=False,
        schema="feature",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_feature_worker_x_feature_worker_id"),
        table_name="worker_x_feature",
        schema="feature",
    )
    op.drop_table("worker_x_feature", schema="feature")
    op.drop_index(
        op.f("ix_feature_image_x_feature_image_id"),
        table_name="image_x_feature",
        schema="feature",
    )
    op.drop_index(
        op.f("ix_feature_image_x_feature_feature_id"),
        table_name="image_x_feature",
        schema="feature",
    )
    op.drop_table("image_x_feature", schema="feature")
    op.drop_index(op.f("ix_worker_worker_name"), table_name="worker", schema="worker")
    op.drop_table("worker", schema="worker")
    op.drop_table("image", schema="image")
    op.drop_table("feature", schema="feature")
    # ### end Alembic commands ###
